INSERT INTO users (username, email, password_hash) VALUES 
('amit_sharma', 'amit.s@example.com', 'password123'), ('ananya_m', 'ananya.m@example.com', 'password123'),
('ishita_s', 'ishita.s@example.com', 'password123'), ('rohan_m', 'rohan.m@example.com', 'password123'),
('kavya_r', 'kavya.r@example.com', 'password123'), ('arjun_k', 'arjun.k@example.com', 'password123'),
('meera_k', 'meera.k@example.com', 'password123'), ('vikram_s', 'vikram.s@example.com', 'password123'),
('nandini_j', 'nandini.j@example.com', 'password123'), ('rahul_d', 'rahul.d@example.com', 'password123'),
('rhea_d', 'rhea.d@example.com', 'password123'), ('sandeep_n', 'sandeep.n@example.com', 'password123'),
('sanya_v', 'sanya.v@example.com', 'password123'), ('varun_b', 'varun.b@example.com', 'password123'),
('tanvi_p', 'tanvi.p@example.com', 'password123'), ('manoj_h', 'manoj.h@example.com', 'password123'),
('vaishnavi_l', 'vaishnavi.l@example.com', 'password123'), ('kartik_f', 'kartik.f@example.com', 'password123'),
('zoya_h', 'zoya.h@example.com', 'password123'), ('akash_t', 'akash.t@example.com', 'password123'),
('aditi_b', 'aditi.b@example.com', 'password123'), ('suresh_z', 'suresh.z@example.com', 'password123'),
('bhavya_c', 'bhavya.c@example.com', 'password123'), ('vinay_o', 'vinay.o@example.com', 'password123'),
('charu_f', 'charu.f@example.com', 'password123'), ('abhishek_y', 'abhishek.y@example.com', 'password123'),
('diya_w', 'diya.w@example.com', 'password123'), ('deepak_k', 'deepak.k@example.com', 'password123'),
('esha_q', 'esha.q@example.com', 'password123'), ('mohan_v', 'mohan.v@example.com', 'password123'),
('falguni_a', 'falguni.a@example.com', 'password123'), ('rajat_r', 'rajat.r@example.com', 'password123'),
('gauri_o', 'gauri.o@example.com', 'password123'), ('yash_g', 'yash.g@example.com', 'password123'),
('hazel_u', 'hazel.u@example.com', 'password123'), ('nikhil_j', 'nikhil.j@example.com', 'password123'),
('ira_y', 'ira.y@example.com', 'password123'), ('prakash_l', 'prakash.l@example.com', 'password123'),
('janhvi_i', 'janhvi.i@example.com', 'password123'), ('vijay_n', 'vijay.n@example.com', 'password123'),
('kiara_k', 'kiara.k@example.com', 'password123'), ('ajay_m', 'ajay.m@example.com', 'password123'),
('lekhana_e', 'lekhana.e@example.com', 'password123'), ('harish_b', 'harish.b@example.com', 'password123'),
('manvi_v', 'manvi.v@example.com', 'password123'), ('mohit_z', 'mohit.z@example.com', 'password123'),
('navya_p', 'navya.p@example.com', 'password123'), ('ganesh_y', 'ganesh.y@example.com', 'password123'),
('oishani_r', 'oishani.r@example.com', 'password123'), ('shivam_t', 'shivam.t@example.com', 'password123');

ALTER TABLE users ALTER COLUMN password_hash DROP NOT NULL;
SELECT * FROM public.users
ORDER BY user_id ASC 

CREATE TABLE ratings (
    rating_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES users(user_id),
    movie_id UUID REFERENCES movies(movie_id),
    rating_value DECIMAL(2,1) CHECK (rating_value >= 0 AND rating_value <= 5),
    created_at TIMESTAMP DEFAULT NOW()
);

INSERT INTO movies (title, genre_main, release_year) VALUES 
('The Northman', 'Action', 2022), ('Everything Everywhere All at Once', 'Sci-Fi', 2022),
('Top Gun: Maverick', 'Action', 2022), ('The Batman', 'Crime', 2022),
('Dune', 'Sci-Fi', 2021), ('The French Dispatch', 'Comedy', 2021),
('Soul', 'Animation', 2020), ('Tenet', 'Sci-Fi', 2020),
('1917', 'War', 2019), ('Knives Out', 'Mystery', 2019),
('Joker', 'Crime', 2019), ('Once Upon a Time in Hollywood', 'Drama', 2019),
('Portrait of a Lady on Fire', 'Romance', 2019), ('The Irishman', 'Crime', 2019),
('Spider-Man: No Way Home', 'Action', 2021), ('Encanto', 'Animation', 2021),
('Belfast', 'Drama', 2021), ('Drive My Car', 'Drama', 2021),
('The Worst Person in the World', 'Romance', 2021), ('CODA', 'Drama', 2021),
('Bohemian Rhapsody', 'Biography', 2018), ('A Star Is Born', 'Drama', 2018),
('Green Book', 'Biography', 2018), ('BlacKkKlansman', 'Crime', 2018),
('The Favourite', 'Comedy', 2018), ('Roma', 'Drama', 2018),
('Coco', 'Animation', 2017), ('Blade Runner 2049', 'Sci-Fi', 2017),
('Dunkirk', 'War', 2017), ('Get Out', 'Horror', 2017),
('Lady Bird', 'Drama', 2017), ('Logan', 'Action', 2017),
('The Shape of Water', 'Fantasy', 2017), ('Three Billboards Outside Ebbing, Missouri', 'Crime', 2017),
('Your Name', 'Animation', 2016), ('Arrival', 'Sci-Fi', 2016),
('La La Land', 'Musical', 2016), ('Manchester by the Sea', 'Drama', 2016),
('Moonlight', 'Drama', 2016), ('The Handmaiden', 'Thriller', 2016),
('Mad Max: Fury Road', 'Action', 2015), ('Inside Out', 'Animation', 2015),
('Room', 'Drama', 2015), ('The Martian', 'Sci-Fi', 2015),
('Spotlight', 'Biography', 2015), ('The Big Short', 'Comedy', 2015),
('Birdman', 'Comedy', 2014), ('Boyhood', 'Drama', 2014),
('Gone Girl', 'Thriller', 2014), ('The Grand Budapest Hotel', 'Comedy', 2014),
('The Imitation Game', 'Biography', 2014), ('Guardians of the Galaxy', 'Action', 2014),
('12 Years a Slave', 'Biography', 2013), ('Gravity', 'Sci-Fi', 2013),
('Prisoners', 'Thriller', 2013), ('The Wolf of Wall Street', 'Biography', 2013),
('Django Unchained', 'Western', 2012), ('The Avengers', 'Action', 2012),
('The Master', 'Drama', 2012), ('Silver Linings Playbook', 'Romance', 2012),
('The Help', 'Drama', 2011), ('Drive', 'Crime', 2011),
('Harry Potter and the Deathly Hallows: Part 2', 'Fantasy', 2011), ('Warrior', 'Action', 2011),
('Black Swan', 'Thriller', 2010), ('The King''s Speech', 'Biography', 2010),
('The Social Network', 'Biography', 2010), ('Toy Story 3', 'Animation', 2010),
('Up', 'Animation', 2009), ('Inglourious Basterds', 'War', 2009),
('The Hurt Locker', 'War', 2008), ('Slumdog Millionaire', 'Drama', 2008),
('WALL-E', 'Animation', 2008), ('No Country for Old Men', 'Crime', 2007),
('There Will Be Blood', 'Drama', 2007), ('Ratatouille', 'Animation', 2007),
('Pan''s Labyrinth', 'Fantasy', 2006), ('Children of Men', 'Sci-Fi', 2006),
('Little Miss Sunshine', 'Comedy', 2006), ('The Lives of Others', 'Thriller', 2006),
('Brokeback Mountain', 'Romance', 2005), ('Batman Begins', 'Action', 2005),
('Million Dollar Baby', 'Drama', 2004), ('Eternal Sunshine of the Spotless Mind', 'Romance', 2004),
('The Incredibles', 'Animation', 2004), ('Howl''s Moving Castle', 'Animation', 2004),
('Finding Nemo', 'Animation', 2003), ('Memories of Murder', 'Crime', 2003),
('Oldboy', 'Thriller', 2003), ('The Pianist', 'Biography', 2002),
('Spirited Away', 'Animation', 2001), ('A Beautiful Mind', 'Biography', 2001),
('Monsters, Inc.', 'Animation', 2001), ('Mulholland Drive', 'Mystery', 2001),
('Requiem for a Dream', 'Drama', 2000), ('Gladiator', 'Action', 2000),
('The Sixth Sense', 'Thriller', 1999), ('American Beauty', 'Drama', 1999),
('The Truman Show', 'Comedy', 1998), ('The Big Lebowski', 'Comedy', 1998);

SELECT movie_id, title, genre_main, release_year FROM movies;
SELECT user_id, username, email FROM users;